configfile: "configfile.yaml"

from settings import working_dir, data_path, metadata_path, output_path, figure_path, script_path

workdir: working_dir

FREQ_BAND = config["FREQ_BAND"]
MIN_STATE_DURATION = config["MIN_STATE_DURATION"]
FIXED_THRESHOLD = config["FIXED_THRESHOLD"]
SIGMA_THRESHOLD = config["SIGMA_THRESHOLD"]
DETRENDING_ORDER = config["DETRENDING_ORDER"]
PSD_NUM_SEG = config["PSD_NUM_SEG"]
PSD_OVERLAP = config["PSD_OVERLAP"]
SLOPE_WINDOW = config["SLOPE_WINDOW"]
# ToDo: isolate loading routine


rule load_enrich_save_neo:
    input:
        data = data_path,
        metadata = metadata_path,
        script = script_path + "load_and_transform_to_neo.py"
    params:
        metadata_dir = os.path.dirname(metadata_path)
    conda:
        "envs/wavescalephant_env.yml"
    output:
        output_path + os.path.splitext(os.path.split(data_path)[1])[0] + ".nix"
    shell:
        """
        export PYTHONPATH='$PYTHONPATH:{params.metadata_dir}'
        python {input.script} --output {output} --data {input.data} \
                              --metadata {input.metadata}
        """


rule log_MUA_estimation:
    input:
        data = {rules.load_enrich_save_neo.output},
        script = script_path + "log_MUA_estimation.py",
        configfile = "configfile.yaml"
    params:
        script_path = script_path,
        freq_band = FREQ_BAND,
        detrending_order = DETRENDING_ORDER,
        psd_num_seg = PSD_NUM_SEG,
        psd_overlap = PSD_OVERLAP
    conda:
        "envs/wavescalephant_env.yml"

    output:
        output_path + "logMUA.nix"
    shell:
        """
        export PYTHONPATH='$PYTHONPATH:{params.script_path}'
        python {input.script} --output {output} \
                              --data {input.data} \
                              --freq_band {params.freq_band} \
                              --detrending_order {params.detrending_order} \
                              --psd_num_seg {params.psd_num_seg} \
                              --psd_overlap {params.psd_overlap}
        """


rule UpDown_detection:
    input:
        logMUA = {rules.log_MUA_estimation.output},
        script = script_path + "UpDown_detection.py"
    params:
        min_state_duration = MIN_STATE_DURATION,
        fixed_threshold = FIXED_THRESHOLD,
        sigma_threshold = SIGMA_THRESHOLD,
        script_path = script_path,
        show_plots = 0
    conda:
        "envs/wavescalephant_env.yml"
    output:
        output_path + "UD_state_vector.npy"
    shell:
        """
        export PYTHONPATH='$PYTHONPATH:{params.script_path}'
        python {input.script} --output {output} --logMUA_estimate {input.logMUA} \
                              --min_state_duration {params.min_state_duration} \
                              --fixed_threshold {params.fixed_threshold} \
                              --sigma_threshold {params.sigma_threshold} \
                              --show_plots {params.show_plots}
        """


### Plotting rules ###

rule plot_signal_traces:
    input:
        data = {rules.load_enrich_save_neo.output},
        script = script_path + "plot_signal_traces.py"
    params:
        scaling = 12,
        show_figure = 0,
        script_path = script_path
    conda:
        "envs/wavescalephant_env.yml"
    output:
        figure_path + "lfp_traces_t{t_start}-{t_stop}s.{format}"
    shell:
        """
        export PYTHONPATH='$PYTHONPATH:{params.script_path}'
        echo {params.show_figure}
        python {input.script} --output {output} --data {input.data} \
                              --format {wildcards.format} --scaling {params.scaling} \
                              --t_start {wildcards.t_start} --t_stop {wildcards.t_stop} \
                              --show_figure {params.show_figure}
        """


rule plot_power_spectrum:
    input:
        data = {rules.load_enrich_save_neo.output},
        script = script_path + "plot_power_spectrum.py"
    params:
        show_figure = 0,
        psd_num_seg = PSD_NUM_SEG,
        psd_overlap = PSD_OVERLAP,
        script_path = script_path
    conda:
        "envs/wavescalephant_env.yml"
    output:
        figure_path + "power_spectrum.{format}"
    shell:
        """
        export PYTHONPATH='$PYTHONPATH:{params.script_path}'
        python {input.script} --output {output} --data {input.data} \
                              --format {format} --psd_num_seg {params.psd_num_seg} \
                              --psd_overlap {params.psd_overlap} \
                              --show_figure {params.show_figure}

        """


rule plot_logMUA_states:
    input:
        logMUA = {rules.log_MUA_estimation.output},
        data = {rules.load_enrich_save_neo.output},
        UD_states = {rules.UpDown_detection.output},
        script = script_path + 'plot_logMUA_states.py'
    params:
        script_path = script_path,
        show_figure = 1
    conda:
        "envs/wavescalephant_env.yml"
    output:
        figure_path + "logMUA_states_channel{channel}_{t_start}-{t_stop}s.{format}"
    shell:
        """
        export PYTHONPATH='$PYTHONPATH:{params.script_path}'
        python {input.script} --output {output} --logMUA {input.logMUA} \
                              --data {input.data} \
                              --UD_states {input.UD_states} \
                              --channel {wildcards.channel} \
                              --format {wildcards.format} \
                              --t_start {wildcards.t_start} \
                              --t_stop {wildcards.t_stop} \
                              --show_figure {params.show_figure}
        """


rule plot_avg_slopes:
    input:
        logMUA = {rules.log_MUA_estimation.output},
        UD_states = {rules.UpDown_detection.output},
        script = script_path + "plot_avg_transitions.py"
    params:
        script_path = script_path,
        slope_window = SLOPE_WINDOW,
        show_figure = 1
    conda:
        "envs/wavescalephant_env.yml"
    output:
        figure_path + "UD_slopes_channel{channel}.{format}"
    shell:
        """
        export PYTHONPATH='$PYTHONPATH:{params.script_path}'
        python {input.script} --output {output} --logMUA_estimate {input.logMUA} \
                              --state_vector {input.UD_states} --show_figure {params.show_figure} \
                              --slope_window {params.slope_window} --channel {wildcards.channel} \
                              --format {wildcards.format}
        """