/* This file was generated by syncqt. */
#ifndef QT_QTUIPLUGIN_VERSION_H
#define QT_QTUIPLUGIN_VERSION_H

#define QTUIPLUGIN_VERSION_STR "5.9.7"

#define QTUIPLUGIN_VERSION 0x050907

#endif // QT_QTUIPLUGIN_VERSION_H
