/* This file was generated by syncqt. */
#ifndef QT_QT3DCORE_VERSION_H
#define QT_QT3DCORE_VERSION_H

#define QT3DCORE_VERSION_STR "5.9.7"

#define QT3DCORE_VERSION 0x050907

#endif // QT_QT3DCORE_VERSION_H
