# Config file for Stage 2 - Processing

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage02_processing'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'LENS'

# Name of the output file
STAGE_OUTPUT: "processed_data.nix"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: 'nix'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [4040, 5050, 6060]  # int or None. default 'None' -> randomly selected
PLOT_FORMAT: 'png'

# The block order determines which processing steps (blocks) will be applied
# and in which order. Execution order is from first to last entry.
# The available blocks are:
# 'background_substraction', 'frequency_filter', 'normalization', 'detrending',
# 'roi_selection', 'logMUA_estimation', 'phase_transform', 'zscore'
# 'deconvolution', 'KDE_characterization'
BLOCK_ORDER: ['roi_selection', 'background_substraction', 'normalization', 'frequency_filter']

# BLOCK - background_substraction
#################################
# No parameters needed

# BLOCK - normalization
#######################
# Normalize the data (devide channels-wise) by either:
# 'mean', 'median', 'max'
NORMALIZE_BY: 'max'

# BLOCK - frequency_filter
##########################
# parameters to be passed to the butterworth frequency filter
# function by elephant
HIGHPASS_FREQ: 0  # in Hz
LOWPASS_FREQ: 5  # in Hz
FILTER_ORDER: 2
# filter function used in scipy backend.
# options: ‘filtfilt’, 'lfilter’, ‘sosfiltfilt’
FILTER_FUNCTION: 'filtfilt'
# Plotting parameters for the power spectrum
PSD_FREQ_RES: 5  # in Hz
PSD_OVERLAP: 0.5

# BLOCK - detrending
####################
# Detrending: 0 - no detrending;
#             1 - mean detrending;
#             2 - mean and slope detrending (linear): this should be the default.
#             3 - quadratic detrending.
#             4 - cubic detrending.
DETRENDING_ORDER: 2

# BLOCK - KDE_characterization
###########################
# Bandwidth of the kernels and fit quantile outliers
# Allowed bandwidths are: 'silverman', 'scott'
BANDWIDTH: 'silverman'
QUANTILE: 0.05

# BLOCK - deconvolution
###########################
# Choose the kernel function used in Fourier deconvolution..
# Allowed functions are: 'lognormal','combination_exp','alpha'.
KERNEL: lognormal
#Parameter list for the chosen kernel:
#alpha : 1:n, 2:tau - combination_exp : 1:trise, 2:tdecay, lognormal : 1:mu, 2:sigma
#ToDo: Put None if you want to search automatically for an optimum parameter, es. None None, or 0.27 None
PARAMETERS: 2.2 0.91

# BLOCK - img_roi_selection
###########################
# Threshold below which the pixels are discarded (set to nan).
# Given in percent of the range between minimum and maximum intensity.
INTENSITY_THRESHOLD: 0.5

# BLOCK - logMUA_estimation
########################
MUA_HIGHPASS_FREQ: 200  # in Hz
MUA_LOWPASS_FREQ: 1500  # in Hz
# Rate of the logMUA signal. Must be <= the original sampling rate
# in Hz (default: 'None', takes highpass_freq)
logMUA_RATE: 100
# Length of time slice (in s) to estimate the local power spectrum
# default 'None', takes minimum number of samples determined
# by the lower bound of the frequency band
FFT_SLICE: 0.1
# PSD_OVERLAP: determined by setting in block frequency_filter
