# Stage 03 Trigger Detection
import os

configfile: os.path.join('configs', 'config_template.yaml')
report: "report.rst"

import sys
utils_path = os.path.join('..', 'scripts')
sys.path.append(os.path.join(os.getcwd(), '..'))
sys.path.append(utils_path)

from settings import output_path
from utils import parse_plot_channels

STAGE_NAME = config["STAGE_NAME"]
STAGE_OUTPUT = config["STAGE_OUTPUT"]
PROFILE = config["PROFILE"]
NEO_FORMAT = config["NEO_FORMAT"]
USE_LINK_AS_STAGE_OUTPUT = config["USE_LINK_AS_STAGE_OUTPUT"]
ADD_UTILS = f"export PYTHONPATH='$PYTHONPATH:{utils_path}'"
OUTPUT_DIR = os.path.join(output_path, PROFILE, STAGE_NAME)

if 'STAGE_INPUT' in config and config['STAGE_INPUT'] is not None:
    STAGE_INPUT = config["STAGE_INPUT"]
else:
    STAGE_INPUT = os.path.join(output_path, PROFILE, 'stage02_processing',
                               'processed_data.nix')

PLOT_TSTART = config["PLOT_TSTART"]
PLOT_TSTOP = config["PLOT_TSTOP"]
PLOT_CHANNELS = parse_plot_channels(config["PLOT_CHANNELS"], STAGE_INPUT)
PLOT_FORMAT = config["PLOT_FORMAT"]

DETECTION_BLOCK = config["DETECTION_BLOCK"]
THRESHOLD_METHOD = config["THRESHOLD_METHOD"]
FIXED_THRESHOLD = config["FIXED_THRESHOLD"]
FIT_FUNCTION = config["FIT_FUNCTION"]
BIN_NUM = config["BIN_NUM"]
SIGMA_FACTOR = config["SIGMA_FACTOR"]
TRANSITION_PHASE = config["TRANSITION_PHASE"]
MINIMA_ORDER = config["MINIMA_ORDER"]


rule all:
    input:
        data = os.path.join(OUTPUT_DIR, DETECTION_BLOCK,
                            'transitions.'+NEO_FORMAT),
        img = os.path.join(OUTPUT_DIR, DETECTION_BLOCK,
                     f'transitions_channel{PLOT_CHANNELS[0]}.'+PLOT_FORMAT),
        configfile = os.path.join('configs', f'config_{PROFILE}.yaml')
    params:
        command = 'ln -s' if USE_LINK_AS_STAGE_OUTPUT else 'cp'
    output:
        data = os.path.join(OUTPUT_DIR, STAGE_OUTPUT),
    shell:
        """
        {params.command} "{input.data}" "{output.data}"
        """


rule plot_trigger_times:
    input:
        data = os.path.join('{dir}', DETECTION_BLOCK,
                            'transitions.'+NEO_FORMAT),
        plot_script = os.path.join('scripts', 'plot_trigger_times.py')
    params:
        tstart = PLOT_TSTART,
        tstop = PLOT_TSTOP,
        plot_channels = PLOT_CHANNELS,
        img = ','.join([os.path.join('{dir}', DETECTION_BLOCK,
                        f'transitions_channel{channel}.'+PLOT_FORMAT)
                        for channel in PLOT_CHANNELS]),
    output:
        img = report(os.path.join('{dir}', DETECTION_BLOCK,
                     f'transitions_channel{PLOT_CHANNELS[0]}.'+PLOT_FORMAT))
    shell:
        """
        {ADD_UTILS}
        python {input.plot_script} --data "{input.data}" \
                                   --output "{params.img}" \
                                   --t_start {params.tstart} \
                                   --t_stop {params.tstop} \
                                   --channels {params.plot_channels} \
        """

rule threshold:
    input:
        data = STAGE_INPUT,
        thresholds = os.path.join('{dir}', 'threshold',
                                  f'{THRESHOLD_METHOD}_thresholds.npy'),
        script = os.path.join('scripts', 'threshold.py')
    output:
        data = os.path.join('{dir}', 'threshold', 'transitions.'+NEO_FORMAT)
    shell:
        """
        {ADD_UTILS}
        python {input.script} --data "{input.data}" \
                              --output "{output.data}" \
                              --thresholds "{input.thresholds}"
        """


rule calc_tresholds_fixed:
    input:
        data = STAGE_INPUT,
        script = os.path.join('scripts', 'calc_thresholds_fixed.py')
    params:
        threshold = FIXED_THRESHOLD
    output:
        array = os.path.join('{dir}', 'threshold', 'fixed_thresholds.npy')
    shell:
        """
        {ADD_UTILS}
        python {input.script} --data "{input.data}" \
                              --output "{output.array}" \
                              --threshold {params.threshold}
        """

rule calc_tresholds_fitted:
    input:
        data = STAGE_INPUT,
        script = os.path.join('scripts', 'calc_thresholds_fitted.py')
    params:
        sigma_factor = SIGMA_FACTOR,
        fit_function = FIT_FUNCTION,
        bin_num = BIN_NUM,
        plot_channels = PLOT_CHANNELS,
        img = ','.join([os.path.join('{dir}', 'threshold',
                        f'amplitudes_channel{channel}.{PLOT_FORMAT}')
                        for channel in PLOT_CHANNELS])
    output:
        array = os.path.join('{dir}', 'threshold', 'fitted_thresholds.npy'),
        img = report(os.path.join('{dir}', 'threshold',
                        f'amplitudes_channel{PLOT_CHANNELS[0]}.{PLOT_FORMAT}'))
    shell:
        """
        {ADD_UTILS}
        python {input.script} --data "{input.data}" \
                              --output "{output.array}" \
                              --output_img "{params.img}" \
                              --sigma_factor {params.sigma_factor} \
                              --fit_function {params.fit_function} \
                              --bin_num {params.bin_num} \
                              --plot_channels {params.plot_channels}
        """

rule hilbert_phase:
    input:
        data = STAGE_INPUT,
        script = os.path.join('scripts', 'hilbert_phase.py')
    params:
        transition_phase = TRANSITION_PHASE,
        plot_channels = PLOT_CHANNELS,
        plot_tstart = PLOT_TSTART,
        plot_tstop = PLOT_TSTOP,
        img = ','.join([os.path.join('{dir}', 'hilbert_phase',
                        f'hilbert_phase_channel{channel}.'+PLOT_FORMAT)
                        for channel in PLOT_CHANNELS])
    output:
        data = os.path.join('{dir}', 'hilbert_phase', 'transitions.'+NEO_FORMAT),
        img = report(os.path.join('{dir}', 'hilbert_phase',
                     f'hilbert_phase_channel{PLOT_CHANNELS[0]}.{PLOT_FORMAT}'))
    shell:
        """
        {ADD_UTILS}
        python {input.script} --data "{input.data}" \
                              --output "{output.data}" \
                              --output_img "{params.img}" \
                              --transition_phase {params.transition_phase} \
                              --plot_channels {params.plot_channels} \
                              --plot_tstart {params.plot_tstart} \
                              --plot_tstart {params.plot_tstart}
        """

rule minima:
    input:
        data = STAGE_INPUT,
        script = os.path.join('scripts', 'minima.py')
    params:
        order = MINIMA_ORDER
    output:
        data = os.path.join('{dir}', 'minima', 'transitions.'+NEO_FORMAT)
    shell:
        """
        {ADD_UTILS}
        python {input.script} --data "{input.data}" \
                              --output "{output.data}" \
                              --order {params.order}
        """
