QT.x11extras_private.VERSION = 5.6.2
QT.x11extras_private.MAJOR_VERSION = 5
QT.x11extras_private.MINOR_VERSION = 6
QT.x11extras_private.PATCH_VERSION = 2
QT.x11extras_private.name = QtX11Extras
QT.x11extras_private.module =
QT.x11extras_private.libs = $$QT_MODULE_LIB_BASE
QT.x11extras_private.includes = $$QT_MODULE_INCLUDE_BASE/QtX11Extras/5.6.2 $$QT_MODULE_INCLUDE_BASE/QtX11Extras/5.6.2/QtX11Extras
QT.x11extras_private.frameworks =
QT.x11extras_private.depends = x11extras
QT.x11extras_private.module_config = v2 internal_module
