QT.webkitwidgets_private.VERSION = 5.6.2
QT.webkitwidgets_private.MAJOR_VERSION = 5
QT.webkitwidgets_private.MINOR_VERSION = 6
QT.webkitwidgets_private.PATCH_VERSION = 2
QT.webkitwidgets_private.name = QtWebKitWidgets
QT.webkitwidgets_private.module =
QT.webkitwidgets_private.libs = $$QT_MODULE_LIB_BASE
QT.webkitwidgets_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebKitWidgets/5.6.2 $$QT_MODULE_INCLUDE_BASE/QtWebKitWidgets/5.6.2/QtWebKitWidgets
QT.webkitwidgets_private.frameworks =
QT.webkitwidgets_private.depends = webkitwidgets
QT.webkitwidgets_private.module_config = v2 internal_module
