QT.webkit_private.VERSION = 5.6.2
QT.webkit_private.MAJOR_VERSION = 5
QT.webkit_private.MINOR_VERSION = 6
QT.webkit_private.PATCH_VERSION = 2
QT.webkit_private.name = QtWebKit
QT.webkit_private.module =
QT.webkit_private.libs = $$QT_MODULE_LIB_BASE
QT.webkit_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebKit/5.6.2 $$QT_MODULE_INCLUDE_BASE/QtWebKit/5.6.2/QtWebKit
QT.webkit_private.frameworks =
QT.webkit_private.depends = webkit
QT.webkit_private.module_config = v2 internal_module
