/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "5.9.7"

#define QTSENSORS_VERSION 0x050907

#endif // QT_QTSENSORS_VERSION_H
